### ISSUE TITLE
Add a ButtonTextColor property

### ISSUE THREAD

**Issue by rrispoli** [newky2k/XamDialogs#1]
It's possible to add a property like "ButtonTextColor" and keep the TitleLabelTextColor" to only change the title and message color?

I'm using XamDialogs with other dialogs (UIAlertControllers) with default black text and colored buttons in my project and I'm looking to maintain a certain pattern of colors.

If I set the color in TitleLabelTextColor, it's change the color of buttons, but also title and message of the dialog, so I prefer to keep the default black color.

Thanks, XamDialogs is awesome! :)

**Comment by newky2k** [comment]
hi, rrispoli,

This has been added as a pull request, https://github.com/newky2k/XamDialogs/pull/2,  I waiting for the author to make a quick change and then I'll merge it in and push out a new version.

Thanks
